theme: minima
title: Millcreek GIS
author: GitHub User
email: bbusch@millcreek.us
description: > # this means to ignore newlines until "baseurl:"
    This will be the direct repo for all python and other code for Millcreek, UT GIS

# social links
twitter_username: @brianbusch1
github_username:  buschbrian

show_excerpts: true # set to false to remove excerpts on the homepage
